CREATE TABLE event_meta(event INTEGER PRIMARY KEY REFERENCES events(id), source INTEGER REFERENCES sources(id), external_id TEXT, parent_external_id TEXT, session TEXT, source_time TEXT, role TEXT, episode INTEGER REFERENCES events(id), scope TEXT NOT NULL DEFAULT '', ingested TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX meta_source_event ON event_meta(source,event);
CREATE INDEX meta_external ON event_meta(source,session,external_id);
CREATE INDEX meta_episode ON event_meta(episode,event);
CREATE TABLE tool_refs(event INTEGER NOT NULL REFERENCES events(id), call_id TEXT NOT NULL, direction TEXT NOT NULL CHECK(direction IN ('call','result')), name TEXT, PRIMARY KEY(event,call_id,direction));
CREATE INDEX tool_refs_call ON tool_refs(call_id,event);
CREATE TABLE captures(task TEXT NOT NULL REFERENCES tasks(id), key TEXT NOT NULL, event INTEGER NOT NULL REFERENCES events(id), PRIMARY KEY(task,key));
ALTER TABLE notes ADD COLUMN scope TEXT NOT NULL DEFAULT '';
ALTER TABLE notes ADD COLUMN event INTEGER REFERENCES events(id);
UPDATE notes SET event=(SELECT e.id FROM events e WHERE e.task=notes.task AND e.kind='note' AND json_valid(e.raw) AND json_extract(e.raw,'$.revision')=notes.id LIMIT 1);
CREATE INDEX notes_scoped ON notes(task,scope,kind,key,id DESC);
CREATE TABLE checkpoints(id INTEGER PRIMARY KEY, task TEXT NOT NULL REFERENCES tasks(id), event INTEGER NOT NULL REFERENCES events(id), snapshot TEXT NOT NULL, created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX checkpoints_task ON checkpoints(task,event);
CREATE TABLE evidence_links(task TEXT NOT NULL REFERENCES tasks(id), event INTEGER NOT NULL REFERENCES events(id), hash TEXT NOT NULL, relation TEXT NOT NULL CHECK(relation IN ('supports','explains','tests')), author TEXT NOT NULL, PRIMARY KEY(task,event,hash,relation), FOREIGN KEY(task,hash) REFERENCES commits(task,hash));
CREATE TABLE enrichments(id INTEGER PRIMARY KEY, task TEXT NOT NULL REFERENCES tasks(id), event INTEGER NOT NULL REFERENCES events(id), text TEXT NOT NULL, author TEXT NOT NULL, created TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(task,event,text,author));
CREATE VIRTUAL TABLE enrichment_fts USING fts5(text,content='enrichments',content_rowid='id');
CREATE TRIGGER enrichment_ai AFTER INSERT ON enrichments BEGIN INSERT INTO enrichment_fts(rowid,text) VALUES(new.id,new.text); END;
PRAGMA user_version=3;
CREATE TABLE checkpoint_commits(checkpoint INTEGER NOT NULL REFERENCES checkpoints(id), hash TEXT NOT NULL, PRIMARY KEY(checkpoint,hash));
DROP TRIGGER events_ai;
DROP TABLE event_fts;
CREATE VIRTUAL TABLE event_fts USING fts5(body,task,content='events',content_rowid='id');
CREATE TRIGGER events_ai AFTER INSERT ON events BEGIN INSERT INTO event_fts(rowid,body,task) VALUES(new.id,new.body,new.task); END;
INSERT INTO event_fts(event_fts) VALUES('rebuild');
